import type { Course } from "@/types/course";

export const FEATURED_COURSES: Course[] = [
  {
    slug: "learn-figma-from-basic",
    title: "Learn Figma from Basic",
    image: "/images/courses/figma-basics.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
  {
    slug: "build-digital-asset",
    title: "Build Digital Asset",
    image: "/images/courses/digital-asset.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
  {
    slug: "the-power-of-big-data",
    title: "the Power of Big Data",
    image: "/images/courses/big-data.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
  {
    slug: "balancing-productivity-and-self-care",
    title: "Balancing Productivity and Self-Care",
    image: "/images/courses/productivity.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
  {
    slug: "mastering-money-management",
    title: "Mastering Money Management",
    image: "/images/courses/money-management.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
  {
    slug: "from-idea-to-startup-success",
    title: "From Idea to Startup Success",
    image: "/images/courses/startup-success.png",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    author: "purepearl studio",
    level: "Beginner",
    studentsLabel: "26+",
    price: 25,
    rating: 4.5,
  },
];

export const COURSE_CATEGORIES: string[] = [
  "Featured",
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Digital Illustration",
  "Film & Video",
  "Crafts",
  "Freelance & Entrepreneurship",
  "Graphic Design",
  "Photography",
  "Productivity",
  "Web Development",
  "Data Science",
  "Cooking",
];
