import type { CourseDetail } from "@/types/course";

export const COURSE_DETAILS: Record<string, CourseDetail> = {
  "build-digital-asset": {
    slug: "build-digital-asset",
    title: "Build Digital Asset: A Comprehensive Guide",
    subtitle: "Unlock the Power of Digital Creation with Expert Guidance",
    heroVideo: "/images/courses/details/hero-video.png",
    level: "Intermediate",
    rating: 4.8,
    reviewCount: 172,
    studentsLabel: "199 Students",
    author: "purepearl studio",
    authorDisplayName: "PurePearl Studio",
    authorRole: "Professional Creator",
    authorAvatar: "/images/avatar-1.png",
    price: 25,
    priceUnit: "/lifetime",
    enrollCta: "Enroll Now",
    description: [
      `Embark on an enlightening exploration into the world of digital creation with our comprehensive course, "Build Digital Assets: A Comprehensive Guide." This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.`,
      `In the initial modules, you'll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.`,
      `As you progress through the course, you'll ascend to higher levels of expertise, delving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.`,
    ],
    sneakPeek: [
      "/images/courses/details/sneak-peek-1.png",
      "/images/courses/details/sneak-peek-2.png",
      "/images/courses/details/sneak-peek-3.png",
      "/images/courses/details/sneak-peek-4.png",
    ],
    keyPoints: [
      "Foundational Concepts",
      "Design Principles Mastery",
      "Advanced Techniques in Digital Creation",
      "Project Showcase and Critique",
      "Optimizing for Various Platforms",
      "Digital Asset Management Best Practices",
      "Monetization Strategies",
      "Capstone Project: Building Your Portfolio",
    ],
    curriculumTitle: "112 Lessons (24 hours)",
    lessons: [
      { order: "01", title: "Introduction to Digital Assets", duration: "12 mins" },
      { order: "02", title: "Design Principles for Impacts", duration: "21 mins" },
      { order: "03", title: "Advanced Techniques in Digital Creation", duration: "16 mins" },
    ],
    moreLessonsLabel: "99 more videos",
    enrollPrompt: "Ready to Dive In? Enroll Now and Start Building Your Digital Future!",
  },
};
